# Shiny Server configuration for PhenoWatch

# Run server as shiny user
run_as shiny;

# Define the server
server {
  listen 3838;
  
  # Serve the phenowatch application at the root path
  location / {
    app_dir /srv/shiny-server/phenowatch;
  }
}
