input <- list()
input$genus <- "Acer"
input$date <- as.Date("2021-04-10")
input$latitude <- 42
input$longitude <- -83
input$event <- "Leaf"
input$status <- "Yes"
input$radius <- 100
input$window <- 14
